/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-10 22:18:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>User and Feedback Dashboard</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: linear-gradient(to right, #f0f4f7, #d1e8ff);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column; /* Allowing vertical stacking of elements */\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-button {\r\n");
      out.write("            background-color: #ff4757; /* Bright red */\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px; /* Rounded corners for a modern look */\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-bottom: 30px; /* Space below the logout button */\r\n");
      out.write("            transition: background-color 0.3s, transform 0.2s;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-button:hover {\r\n");
      out.write("            background-color: #ff6b81; /* Lighter red on hover */\r\n");
      out.write("            transform: scale(1.05); /* Slightly enlarge on hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 30px; /* Space between boxes */\r\n");
      out.write("            justify-content: center; /* Center boxes */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .box {\r\n");
      out.write("            background-color: #ffffff; /* White background */\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 30px; /* Increased padding */\r\n");
      out.write("            width: 250px; /* Slightly wider boxes */\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1); /* More pronounced shadow */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s; /* Smooth transitions */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .box:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.2); /* Shadow change on hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .box h3 {\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            color: #333; /* Darker text for readability */\r\n");
      out.write("            font-size: 24px; /* Larger title */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .count {\r\n");
      out.write("            font-size: 3em; /* Larger count */\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button {\r\n");
      out.write("            background-color: #007bff; /* Bootstrap primary blue */\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s, transform 0.2s;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button:hover {\r\n");
      out.write("            background-color: #0056b3; /* Darker blue on hover */\r\n");
      out.write("            transform: translateY(-2px); /* Lift effect on hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Colorful Box Styles */\r\n");
      out.write("        .users-box {\r\n");
      out.write("            background-color: #e0f7fa; /* Light cyan */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feedbacks-box {\r\n");
      out.write("            background-color: #ffe0b2; /* Light amber */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- Users Box -->\r\n");
      out.write("        <div class=\"box users-box\">\r\n");
      out.write("            <h3>All Users</h3>\r\n");
      out.write("            <div class=\"count\">\r\n");
      out.write("		");
      out.print( request.getAttribute("userCount") != null ? (Integer) request.getAttribute("userCount") : 0 );
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"button\" onclick=\"window.location.href='FetchUserServlet'\">View Users</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Feedbacks Box -->\r\n");
      out.write("        <div class=\"box feedbacks-box\">\r\n");
      out.write("            <h3>All Feedbacks</h3>\r\n");
      out.write("            <div class=\"count\">\r\n");
      out.write("                ");
      out.print( request.getAttribute("feedbackCount") != null ? (Integer) request.getAttribute("feedbackCount") : 0 );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"button\" onclick=\"window.location.href='AdminGetAllFeedBackServlet'\">View Feedbacks</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout Button -->\r\n");
      out.write("    <br/><br/><br/> \r\n");
      out.write("    <button class=\"logout-button\" onclick=\"window.location.href='AdminLogin.jsp'\">Logout</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
